# -------------------------------------
# ---- Implemented on my LED Strip board in bedroom headboard ----
# -------------------------------------
substitutions:
  devicename: bedroom_strip

esphome:
  name: ${devicename}
  platform: ESP8266
  board: nodemcuv2

wifi:
  #power_save_mode: light # power reduced from 1.2w to 0.8w
  #fast_connect: true
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    hidden: True
  manual_ip:
    static_ip: !secret ip_bedroom_strip
    gateway: !secret ip_gateway
    subnet: 255.255.255.0
  domain: .homelan
  ap: # Enable fallback hotspot (captive portal) in case wifi connection fails
    ssid: "${devicename} Hotspot"
    password: !secret password

captive_portal:

#mqtt:
#  broker: !secret mqtt_host
#  username: !secret mqtt_username
#  password: !secret mqtt_password
#  reboot_timeout: 0s # Dont reboot..

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret password
  reboot_timeout: 0s # Dont reboot..

ota:
  password: !secret password

web_server:
  port: 80
  auth:
    username: admin
    password: !secret password


# Dam thing always flashes
#status_led:
#  pin:
#    number: GPIO16
#    inverted: True

light:
  - platform: neopixelbus
    type: RGB #GRB??
#    variant: WS2811 #Needed??
    pin: GPIO3 #Solder time
    power_supply: mosfet
    num_leds: 40
    name: Bed Lightstrip LED
    id: leds
    effects:
      - flicker:
      - strobe:
      - random:
      - addressable_rainbow:
          width: 40      
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:

# https://esphome.io/components/power_supply.html
power_supply:
  - id: mosfet
    enable_time: 50ms
    keep_on_time: 2s
    pin:
      number: GPIO13
      inverted: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: True
    name: Bed Switch Top 
    filters:
      - delayed_on: 10ms
    
  - platform: gpio
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: True
    name: Bed Switch Middle
    filters:
      - delayed_on: 10ms
      
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    name: Bed Switch Bottom
    filters:
      - delayed_on: 10ms    