# -------------------------------------
# ---- NOT Implemented yet ----
# -------------------------------------
substitutions:
  devicename: media-ceiling

esphome:
  name: ${devicename}
  platform: ESP8266
  board: nodemcuv2

wifi:
  #power_save_mode: light # power reduced from 1.2w to 0.8w
  #fast_connect: true
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    hidden: True
  manual_ip:
    static_ip: !secret ip_media_ceiling
    gateway: !secret ip_gateway
    subnet: 255.255.255.0
  domain: .homelan
  ap: # Enable fallback hotspot (captive portal) in case wifi connection fails
    ssid: "${devicename} Hotspot"
    password: !secret password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 0s # Dont reboot..
  encryption:
    key: !secret encryption_key

ota:
  password: !secret password

web_server:
  port: 80
  auth:
    username: admin
    password: !secret password


light:
  - platform: status_led
    id: statled
    pin:
      number: GPIO2
      inverted: true

  - platform: neopixelbus
    type: GRBW
    variant: WS2811
    pin: GPIO3
    num_leds: 5
    name: "${devicename} Lights"
    id: leds
    effects:
      - flicker:
      - strobe:
      - random:
      - addressable_rainbow:
          width: 40      
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker: