# -------------------------------------
# ---- Implemented on Mirabella Genio Wi-Fi Power Plug with Energy Monitoring ----
# https://templates.blakadder.com/mirabella_genio_42905868.html
# -------------------------------------
substitutions:
  devicename: mirabella_genio_gpo

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp8285

wifi:
  #power_save_mode: light # power reduced from 1.2w to 0.8w
  #fast_connect: true
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    hidden: True
  manual_ip:
    static_ip: !secret ip_mirabella_genio_gpo
    gateway: !secret ip_gateway
    subnet: 255.255.255.0
  domain: .homelan
  ap: # Enable fallback hotspot (captive portal) in case wifi connection fails
    ssid: "${devicename} Hotspot"
    password: !secret password

captive_portal:

#mqtt:
#  broker: !secret mqtt_host
#  username: !secret mqtt_username
#  password: !secret mqtt_password
#  reboot_timeout: 0s # Dont reboot..

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret password
  reboot_timeout: 0s # Dont reboot..

ota:
  password: !secret password

web_server:
  port: 80
  auth:
    username: admin
    password: !secret password


sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current_resistor: 0.002500
#    current_resistor: 0.002600 100w low
#    current_resistor: 0.002770 200w low
    voltage_divider: 829
#    voltage_divider: 800 9.2v under
#    voltage_divider: 1000 53v over
#    voltage_divider: 922 30v over
    current:
      name: ${devicename} Current
      unit_of_measurement: A
    voltage:
      name: ${devicename} Voltage
      unit_of_measurement: V
    power:
      name: ${devicename} Power
      id: switch_power
      unit_of_measurement: W
    change_mode_every: 1
    update_interval: 2s


binary_sensor:
  - platform: gpio
    id: button_1
    pin: GPIO03
    on_press:
      then:
        - switch.toggle: relay_1


switch:
  - platform: gpio
    id: relay_1
    name: ${devicename} Relay
    pin:
      number: GPIO14
      inverted: no


status_led:
  pin:
    number: GPIO13
    inverted: yes
