# -------------------------------------
# ---- Implemented on Mirabella Genio RGBW Globe ----
# -------------------------------------
substitutions:
  devicename: mirabella_genio_rgbw_a

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp8285

wifi:
  #power_save_mode: light # power reduced from 1.2w to 0.8w
  #fast_connect: true
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    hidden: True
  manual_ip:
    static_ip: !secret ip_geniorgbw_a_light
    gateway: !secret ip_gateway
    subnet: 255.255.255.0
  domain: .homelan
  ap: # Enable fallback hotspot (captive portal) in case wifi connection fails
    ssid: "${devicename} Hotspot"
    password: !secret password

captive_portal:

#mqtt:
#  broker: !secret mqtt_host
#  username: !secret mqtt_username
#  password: !secret mqtt_password
#  reboot_timeout: 0s # Dont reboot..

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret password
  reboot_timeout: 0s # Dont reboot..

ota:
  password: !secret password

web_server:
  port: 80
  auth:
    username: admin
    password: !secret password


sm2135:
  data_pin: GPIO12
  clock_pin: GPIO14
  
output:
  - platform: sm2135
    id: output_green
    channel: 0
    max_power: 0.46
  - platform: sm2135
    id: output_blue
    channel: 1
    max_power: 0.3
  - platform: sm2135
    id: output_red
    channel: 2
  - platform: sm2135
    id: output_white
    channel: 3
    max_power: 0.8
  - platform: sm2135
    id: output_warmwhite
    channel: 4
    max_power: 0.8

light:
  - platform: rgbw
    name: "mirabella_genio_rgbw_a"
    default_transition_length: 1s
    red: output_red
    green: output_green
    blue: output_blue
    white: output_warmwhite
    restore_mode: ALWAYS_ON # Ensure the light turns on by default if the physical switch is actuated.
#    effects:
#      - strobe:
#      - flicker:
#      - random:
#      - random:
#          name: "My Slow Random Effect"
#          transition_length: 30s
#          update_interval: 30s
#      - random:
#          name: "My Fast Random Effect"
#          transition_length: 4s
#          update_interval: 5s  