# -------------------------------------
# ---- Implemented on ESP07 in Roof ----
# -------------------------------------
substitutions:
  devicename: roof_minder

esphome:
  name: ${devicename}
  platform: ESP8266
  #board: esp07
  board: esp01_1m

wifi:
  #power_save_mode: light # power reduced from ?.?w to ?.?w
  #fast_connect: true
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    hidden: True
  manual_ip:
    static_ip: !secret ip_roof_minder
    gateway: !secret ip_gateway
    subnet: 255.255.255.0
  domain: .homelan
  ap: # Enable fallback hotspot (captive portal) in case wifi connection fails
    ssid: "${devicename} Hotspot"
    password: !secret password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 0s # Dont reboot..
  encryption:
    key: !secret encryption_key

ota:
  password: !secret password

web_server:
  port: 80
  auth:
    username: admin
    password: !secret password


sensor:
  - platform: dht
    pin: GPIO12
    model: AM2302
    temperature:
      name: "Roof Temperature"
    humidity:
      name: "Roof Humidity"
    update_interval: 5min