# -------------------------------------
# ---- Implemented on D1 mini on side of external water tank ----
# ---- v1.2
# -------------------------------------

esphome:
  name: tank_minder
  platform: ESP8266
  board: esp01_1m

wifi:
  power_save_mode: light # power reduced from ?.?w to ?.?w
  #fast_connect: true
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    hidden: True
  manual_ip:
    static_ip: !secret ip_tank_minder
    gateway: !secret ip_gateway
    subnet: 255.255.255.0
  ap: # Enable fallback hotspot (captive portal) in case wifi connection fails
    ssid: "TankMinder Fallback Hotspot"
    password: !secret password

captive_portal:

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  reboot_timeout: 0s # Dont reboot..

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret password
  reboot_timeout: 0s # Dont reboot..

ota:
  password: !secret password


i2c:
  sda: GPIO4
  scl: GPIO5
  id: bus_a
#  scan: True

ads1115: #https://esphome.io/components/sensor/ads1115.html
  - address: 0x48

sensor:
  - platform: ads1115
    id: adclevel
    multiplexer: 'A0_GND'
#    gain: 6.144 #(measures up to 6.144V)
#    gain: 4.096 #(measures up to 4.096V)
    gain: 2.048 #(measures up to 2.048V) #Full hose pressure is just shy of 2v
#    gain: 1.024 #(measures up to 1.024V)
#    gain: 0.512 #(measures up to 0.512V)
#    gain: 0.256 #(measures up to 0.256V)    
    name: "Water Tank Level"
    icon: "mdi:cup-water"
    accuracy_decimals: 0
    unit_of_measurement: "L"
    update_interval: 2min
#    update_interval: 30s
    filters:
    - calibrate_linear: # https://esphome.io/components/sensor/index.html#sensor-filters
#     Map 0.0 (from sensor) to 0.0 (true value)  
      - 0.490 -> 0.0 # Empty Value
      - 0.546 -> 3000.0 # Full Value
#    - median:
#        window_size: 10
#        send_every: 5

  - platform: template
    name: "Water Tank Status"
    update_interval: 2min
    unit_of_measurement: '%'
    icon: "mdi:water-percent"
    accuracy_decimals: 0
    lambda: |-
      return ((id(adclevel).state / 3000) * 100.00);




#binary_sensor:
#  - platform: gpio
#    pin:
#      number: GPIO14
#      mode: INPUT_PULLUP
#      inverted: True
#    name: "Water Tank Pump On"
#    device_class: moisture
#    filters:
#      - delayed_on: 10ms
#      - delayed_off: 10ms
#      
#  - platform: gpio
#    pin:
#      number: GPIO12
#      mode: INPUT_PULLUP
#      inverted: True
#    name: "Water Tank Rain Water"
#    filters:
#      - delayed_on: 10ms
#      - delayed_off: 10ms
#
#  - platform: gpio
#    pin:
#      number: GPIO13
#      mode: INPUT_PULLUP
#      inverted: True
#    name: "Water Tank Mains Water"
#    filters:
#      - delayed_on: 10ms
#      - delayed_off: 10ms
#
#  - platform: gpio
#    pin:
#      number: GPIO15
#      mode: INPUT_PULLUP
#      inverted: True
#    name: "Water Tank Warning"
#    device_class: safety
#    filters:
#      - delayed_on: 10ms
#      - delayed_off: 10ms
