# -------------------------------------
# ---- Implemented on ESP07 in Box ----
# -------------------------------------
substitutions:
  devicename: wine_minder

esphome:
  name: ${devicename}
  platform: ESP8266
  #board: esp07
  board: esp01_1m

wifi:
  #power_save_mode: light # power reduced from ?.?w to ?.?w
  #fast_connect: true
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    hidden: True
  manual_ip:
    static_ip: !secret ip_wine_minder
    gateway: !secret ip_gateway
    subnet: 255.255.255.0
  domain: .homelan
  ap: # Enable fallback hotspot (captive portal) in case wifi connection fails
    ssid: "${devicename} Hotspot"
    password: !secret password

captive_portal:

#mqtt:
#  broker: !secret mqtt_host
#  username: !secret mqtt_username
#  password: !secret mqtt_password
#  reboot_timeout: 0s # Dont reboot..

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret password
  reboot_timeout: 0s # Dont reboot..

ota:
  password: !secret password

web_server:
  port: 80
  auth:
    username: admin
    password: !secret password


sensor:
  - platform: dht
    pin: GPIO4
    model: AM2302
    temperature:
      name: "${devicename} Outside Temperature"
    humidity:
      name: "${devicename} Outside Humidity"
    update_interval: 1min

  - platform: dht
    pin: GPIO0
    model: AM2302
    temperature:
      name: "${devicename} Bottom Temperature"
    humidity:
      name: "${devicename} Bottom Humidity"
      id: humBot
    update_interval: 5min

  - platform: dht
    pin: GPIO3
    model: AM2302
    temperature:
      name: "${devicename} Top Temperature"
    humidity:
      name: "${devicename} Top Humidity"
      id: humTop
    update_interval: 5min


binary_sensor:
  - platform: template
    name: "${devicename} Bottom Problem"
    device_class: moisture
    lambda: |-
      if (id(humBot).state >= 45 && id(humBot).state <= 55) {
        return false;
      } else {
        return true;
      }

  - platform: template
    name: "${devicename} Top Problem"
    device_class: moisture
    lambda: |-
      if (id(humTop).state >= 45 && id(humTop).state <= 55) {
        return false;
      } else {
        return true;
      }      